package presenters;

public enum Events {
    ADD_PROCESS, EDIT_PROCESS, DELETE_PROCESS, ACCEPT_EDIT_PROCESS, ACCEPT_ADD_PROCESS, CANCEL_EDIT_PROCESS,
    CANCEL_ADD_PROCESS, INIT_SIMULATION, EXIT, NEW_SIMULATION
}
